# ... (environment section)

scripts:
  - name: Flutter pub get
    script: |
      flutter pub get

  - name: Run Unit and Widget Tests  <-- THIS IS THE MISSING STEP
    script: |
      flutter test --coverage 

  - name: Building Android # The next step in your current log
    # ...