# In codemagic.yaml
workflows:
  default-build:
    # ... (environment and integrations sections) ...
    
    scripts:
      - name: Flutter pub get
        script: |
          flutter pub get

      - name: Run Unit and Widget Tests 
        script: |
          # 1. Ensure the coverage file is created
          flutter test --coverage 
          
      - name: Build Android App # Explicit build command to follow the tests
        script: |
          flutter build apk --debug --target-platform android-arm64
          
      # Add other build steps as needed
      # - name: Building iOS App
      #   script: |
      #     flutter build ios --no-codesign
          
    # ... (artifacts and triggering sections) ...