// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtX9sUz31FCgWbxoDFoEw2d9x7Sysai2M',
    appId: '1:1005775262660:web:24443e32745335c6a7ca91',
    messagingSenderId: '1005775262660',
    projectId: 'ditonton-final-d3a60',
    authDomain: 'ditonton-final-d3a60.firebaseapp.com',
    storageBucket: 'ditonton-final-d3a60.firebasestorage.app',
    measurementId: 'G-ECLKDVWS8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvy0mf9GK4vQuTgjtMXIUHvYrHljR8q7c',
    appId: '1:1005775262660:android:a55a23d7160b2264a7ca91',
    messagingSenderId: '1005775262660',
    projectId: 'ditonton-final-d3a60',
    storageBucket: 'ditonton-final-d3a60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMa5CPbMgYVf5jKoDidAht5HZZXM1pRg8',
    appId: '1:1005775262660:ios:4aca374214c0dd07a7ca91',
    messagingSenderId: '1005775262660',
    projectId: 'ditonton-final-d3a60',
    storageBucket: 'ditonton-final-d3a60.firebasestorage.app',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
